default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Easy_Riding_development

test:
  <<: *default
  database: Easy_Riding_test

		production:
		<<: *default
			database: store_production
			username: <%= ENV['POSTRGES_USERNAME'] %>
			password: <%= ENV['STORE_DATABASE_PASSWORD'] %>
			secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

